apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-staic
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08302bb340cf1ae85

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-staic
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-staic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi