kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-roboshop
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-049eacf97918cfecb
  directoryPerms: "700"
  basePath: "/roboshop" # /roboshop/cart


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-roboshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-roboshop

---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port