apiVersion: v1
kind: Pod
metadata:
  name: multi-conrainer
  labels: 
    project: roboshop
    purpose: multicontaine-demo
spec:
  containers:
  - name: nginx
    iamge: nginx
  - name: alamalinux
    image: alamalinux
  