apiVersion: v1
kind: Pod
metadata:
  name: multi-conrainer
  lables: 
    project: roboshop
    purpose: multicontaine-demo
spec:
  container:
  - name: nginx
    iamge: nginx
  - name: alamalinux
    image: alamalinux
  