apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    environment: dev
spec:
  containers: 
  - name: app
    image: nginx
    resources:
      requests: #soft limit
        memory: "64Mi" 
        cpu: "250m"
      limits: # hard limit
        memory: "128Mi"
        cpu: "500m"