apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: nginx
    env:
    - name: COURSE
      value: "K8S"
    - name: TRAINER
      value: "SIVA KUMAR"
