apiVersion: v1
kind: Service
metadata:
  name: nginx-naresh-lb # service name
  labels:
    purpose: service-lb-demo
spec:
  type: NodePort
  selector:
    purpose: service-lb-demo
    project: roboshop
    env: dev
  ports: 
  - name: http
    protocol:  TCP
    port: 80 # service port
    targetPort: 80 # container port

---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-lb
  labels:
    purpose: service-lb-demo
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx