apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx  
  labels: 
    # replica set labels
    purpose: ds-demo
    project: roboshop
    environment: dev
    app: nginx
spec:
  replicas: 2
  # these are the labels replica set use to crete pod replicas, this should match pod labels 
  selector:
    matchLabels:
      purpose: ds-demo
      project: roboshop
      environment: dev
      app: nginx

  # this pod defination    
  template:
    metadata:
      labels:
        purpose: ds-demo
        project: roboshop
        environment: dev
        app: nginx       
    spec:
      containers:
      - name: nginx
        #image: nginx:stable-perl
        image: nginx